DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS listr;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  root INTEGER UNIQUE NOT NULL
);


CREATE TABLE listr (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user INTEGER NOT NULL,
    parent INTEGER NOT NULL,
    task TEXT NOT NULL,
    completed INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT parent_fk
    FOREIGN KEY(parent) REFERENCES listr (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
    CONSTRAINT user_fk
    FOREIGN KEY(user) REFERENCES users (id)
);