DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS listr;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);


CREATE TABLE IF NOT EXISTS listr (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user INTEGER NOT NULL,
    parent INTEGER NOT NULL,
    task TEXT NOT NULL,
    completed INTEGER NOT NULL,
    CONSTRAINT parent_fk
    FOREIGN KEY(parent) REFERENCES listr (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
    CONSTRAINT user_fk
    FOREIGN KEY(user) REFERENCES users (id)
);